### PR TITLE
fixed some crashes, added None data as WARN state

### PR DESCRIPTION
**Pull request by kleinski**
Hello Andreas, 

we fixed some crashes, which occurred because of missing data.

Kind regards, 

Marcus

### CODE REVIEW

**Comment by kleinski** [comment]
Sorry, two files slipped in with changes only of a formatting kind:
* storage and drives

Logical changes are contained in network and the utils file dell_idrac.

Please ignore the changes of storage and drives.

Kind regards, 

Marcus

**Comment by Yogibaer75** [comment]
The changes in network ok, i see the problem. But why the changes inside the utils?
If there is no data then the state is ignored. Do you have an output example of such a case?

**Comment by Yogibaer75** [comment]
For the network i have also a small request. I had no, under any circumstances, a system without a network interface.
If possible i would also take a small output from the special agent for such a system. Only the interface section without interfaces :)

**Comment by kleinski** [comment]
Hello Andreas,

I will check if it's possible to give you that output.

Kind regards,

Marcus

Am Mo., 1. Aug. 2022 um 14:47 Uhr schrieb Andreas Döhler <
***@***.***>:

**Comment by kleinski** [comment]
Hello Andreas,

here is the traceback of the crash:

  File "/omd/sites/test/lib/python3/cmk/base/checking.py", line 564,
in get_aggregated_result
    result = _aggregate_results(check_function(**kwargs))
  File "/omd/sites/test/lib/python3/cmk/base/checking.py", line 796,
in _aggregate_results
    perfdata, results = _consume_and_dispatch_result_types(subresults)
  File "/omd/sites/test/lib/python3/cmk/base/checking.py", line 840,
in _consume_and_dispatch_result_types
    for subr in subresults:
  File "/omd/sites/test/lib/python3/cmk/base/api/agent_based/register/check_plugins.py",
line 89, in filtered_generator
    for element in generator(*args, **kwargs):
  File "/omd/sites/test/local/lib/python3/cmk/base/plugins/agent_based/dell_idrac_rf_voltage.py",
line 62, in check_dell_idrac_rf_voltage
    dev_state, dev_msg = idrac_health_state(voltage["Status"])
  File "/omd/sites/test/local/lib/python3/cmk/base/plugins/agent_based/utils/dell_idrac.py",
line 102, in idrac_health_state
    temp_state, state_msg = state_map.get(state[key])


Am Mo., 1. Aug. 2022 um 14:45 Uhr schrieb Andreas Döhler <
***@***.***>:

**Comment by Yogibaer75** [comment]
If the state[key] value is "None" then it should not reach this point in the code.
Is it possible that the last line from the traceback is missing? As there is no real error message.

**Comment by kleinski** [comment]
Hello Andreas,

no, the traceback is complete:
image


I can mail you the crash report.

Kind regards

Marcus

Am Mo., 1. Aug. 2022 um 16:59 Uhr schrieb Andreas Döhler <
***@***.***>:

**Comment by Yogibaer75** [comment]
Fixed the problem a little bit different with this commit
https://github.com/Yogibaer75/Check_MK-Things/commit/6ac2988656f1c003281749dcf809679302c73613

Also some formatting cleanups done

**Comment by kleinski** [comment]
Hello Andreas,

would you send me your email address?
I will send that output to you.

Kind regards,

Marcus

Am Mo., 1. Aug. 2022 um 16:00 Uhr schrieb Marcus Klein ***@***.***>:

**Comment by Yogibaer75** [comment]
Is version 1.5 not working?
Normally the problem from your last crash should be gone with the fix.

**Pull request closed without merging**
