### PR TITLE
Merge with nutanix special agent from Kevin Tijssen

### PR DESCRIPTION
**Pull request by jwiederh**
Hi Andreas,
I completed your nutanix-Agent with the missing data from Kevin Tijssen's Special Agent (https://exchange.checkmk.com/p/agent-ntnx).

Newly added are:
Prism HA-state
Cluster CPU and Memory
Cluster-Wide Controller IO Bandwith/IOPS/Latency
Data Protection

If you got any ideas how to improve the agent further or questions regarding the changes I made, let me know :)

Cheers Jeronimo

### CODE REVIEW

**Comment by Yogibaer75** [comment]
Hi Jeronimo,

nice to see the missing checks. Can you please check why there are some many identical files shown as complete new?
Is this a line ending problem?

If i have some time this week i can have a look at the new checks. It is possible that i can include these new checks also in my PR against the master tribe29 repo.
My PR is nearly finished there :)

br
Andreas

**Comment by jwiederh** [comment]
Hi, not sure about that. I use gitlab for myself, so maybe there is some meta-info that got added. I'll look into it when I have the time.

And sure, go ahead with the PR for t29. :)

Cheers Jeronimo

**Comment by Yogibaer75** [comment]
I modified all your new checks to a format accepted by tribe29.
Now we will see if they accept complete PR (over 90 new or modified files).
I will also make a mkp with all the checks as they are now inside the PR.
If this rework is done i will close this PR here.

**Comment by Yogibaer75** [comment]
Uploaded the version from the official PR i hope it works like i expect :)

**Pull request closed without merging**
